name: pikpakAutoInvite
on:
  workflow_dispatch:
  schedule:
    # 每天新加坡时间凌晨 00:00:01 执行
    - cron:  '1 16 * * *'
  push:
    branches:
      - master

jobs:
  run-python-script:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - run: pip install -r requirements.txt
        # 修改为12小时内随机执行
      - name: Random sleep
        run: |
          SECONDS=$((RANDOM % 43200))
          echo "Sleeping for $SECONDS seconds"
          sleep $SECONDS
      - run: python pikpakAutoInvite.py
